#!/bin/bash

version="-std=c99"

gcc $version -o keygen ./keygen.c
gcc $version -o otp_enc ./otp_enc.c
gcc $version -o otp_enc_d ./otp_enc_d.c
gcc $version -o otp_dec ./otp_dec.c
gcc $version -o otp_dec_d ./otp_dec_d.c
